### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 94burns** [PhilippImhof/FromSamToGarm#2]
![Screenshot 2024-12-08 214318](https://github.com/user-attachments/assets/d6c29455-a008-4e96-8316-a5dbbb74d1da)
![Screenshot 2024-12-08 214245](https://github.com/user-attachments/assets/26600c5f-dcdf-4ac4-bcca-f97615e269f2)

Thank you for this, Managed to get my exercises in. However for activity and weight I get these messages, any ideas? thanks

**Comment by PhilippImhof** [comment]
Hello and thanks for reaching out. 

The first error means that the date/time is not stored as a timestamp (which it should be according to the docs), but in ISO format. The second error means that the height has not been set; in that case it makes sense to assume 0.

Could you please download the scripts from the following branch and tell me, whether they solve your problems?

https://github.com/PhilippImhof/FromSamToGarm/tree/issue-2

**Comment by PhilippImhof** [comment]
@94burns Have you tried the fix?

**Comment by AstraJens** [comment]
this is the output from my rpi5 

root@raspberrypi5:/home/pi/AAA# python activity.py
Traceback (most recent call last):
  File "/home/pi/AAA/activity.py", line 184, in <module>
    data = merge_data(fetch_floor_data(), fetch_calorie_data(), fetch_activity_data())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/AAA/activity.py", line 117, in merge_data
    merged_data[date]["Calories"] = 0
    ~~~~~~~~~~~^^^^^^
KeyError: '2017-04-04'
root@raspberrypi5:/home/pi/AAA#

**Comment by PhilippImhof** [comment]
Thanks @AstraJens 

These errors (although silly) are sometimes difficult for me to catch, because I only have the data from my own export and it worked fine. I have pushed a correction to the branch linked above
