### ISSUE TITLE
Error line 17    activity.py

### ISSUE THREAD

**Issue by AstraJens** [PhilippImhof/FromSamToGarm#4]
PS C:\Users\Jens> & C:/Users/Jens/AppData/Local/Microsoft/WindowsApps/python3.11.exe s:/AAA/samsunghealth_astrajens1_20241130133710/activity.py
Traceback (most recent call last):
  File "s:\AAA\samsunghealth_astrajens1_20241130133710\activity.py", line 184, in <module>
    data = merge_data(fetch_floor_data(), fetch_calorie_data(), fetch_activity_data())
                      ^^^^^^^^^^^^^^^^^^
  File "s:\AAA\samsunghealth_astrajens1_20241130133710\activity.py", line 17, in fetch_floor_data
    raise Exception("No floors data found.")
Exception: No floors data found.

**Comment by PhilippImhof** [comment]
Hello. This exception is raised on purpose. It means that the data regarding the number of floors climbed could not be found in your export. Can you check whether you have files matching `com.samsung.health.floors_climbed.*.csv` ?

**Comment by PhilippImhof** [comment]
You might want to try an update version from this branch:

https://github.com/PhilippImhof/FromSamToGarm/tree/issue-3


Please tell me, if that works for you. It will inform that no floor data could be found, but continue anyway.

**Comment by AstraJens** [comment]
yes i have     com.samsung.health.floors_climbed.20241130133710.csv

with Visual Code Studio
PS C:\Users\Jens> & C:/Users/Jens/AppData/Local/Microsoft/WindowsApps/python3.11.exe s:/AAA/samsunghealth_astrajens1_20241130133710/activity.py
s:\AAA\samsunghealth_astrajens1_20241130133710\activity.py:19: UserWarning: No floor data found.
  warnings.warn("No floor data found.")
s:\AAA\samsunghealth_astrajens1_20241130133710\activity.py:48: UserWarning: No calorie data found.
  warnings.warn("No calorie data found.")
s:\AAA\samsunghealth_astrajens1_20241130133710\activity.py:76: UserWarning: No activity data found.
  warnings.warn("No activity data found.")



on my raspberrypi5

pi@raspberrypi5:~/AAA $ python activity.py
Traceback (most recent call last):
  File "/home/pi/AAA/activity.py", line 184, in <module>
    data = merge_data(fetch_floor_data(), fetch_calorie_data(), fetch_activity_data())
                                                                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/AAA/activity.py", line 87, in fetch_activity_data
    int(row["day_time"]) / 1000
    ^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '2023-12-30 00:00:00.000'

**Comment by PhilippImhof** [comment]
If the script cannot find calories, floors climbed and weight, you are probably running it in the wrong directory.

The error you get on the raspberry pi comes from malformed data in the CSV. This has been addressed in issue #2, I am waiting for feedback from the reporter. You might want to check it out as well.

**Comment by AstraJens** [comment]
.\files
.\json
*.csv

i use this activity.py on root directory... where the .csv files are saved. i tried it in the different directory's
The weight.py is working...

**Comment by PhilippImhof** [comment]
That is very strange, because I simply use `glob` to check for the files, so there is not much that could go wrong.

Would you mind posting the list of CSV files you have in that directory? You could probably do something like:

```
C:\yourpath> dir com.samsung.health.floors_climbed.*.csv
C:\yourpath> dir com.samsung.shealth.calories_burned.details.*.csv
C:\yourpath> dir com.samsung.shealth.activity.day_summary.*.csv
```

**Comment by AstraJens** [comment]
Only one file from all of these three types



S:\AAA\samsunghealth>dir com.samsung.health.floors_climbed.*.csv
 Datenträger in Laufwerk S: ist Volume HD 6TB
 Volumeseriennummer: 84D6-63CE

 Verzeichnis von S:\AAA\samsunghealth

14.12.2024  12:18         2.215.474 com.samsung.health.floors_climbed.20241214121856.csv
               1 Datei(en),      2.215.474 Bytes
               0 Verzeichnis(se), 3.274.738.540.544 Bytes frei

S:\AAA\samsunghealth>dir com.samsung.shealth.calories_burned.details.*.csv
 Datenträger in Laufwerk S: ist Volume HD 6TB
 Volumeseriennummer: 84D6-63CE

 Verzeichnis von S:\AAA\samsunghealth

14.12.2024  12:19           624.876 com.samsung.shealth.calories_burned.details.20241214121856.csv
               1 Datei(en),        624.876 Bytes
               0 Verzeichnis(se), 3.274.738.540.544 Bytes frei

S:\AAA\samsunghealth>dir com.samsung.shealth.activity.day_summary.*.csv
 Datenträger in Laufwerk S: ist Volume HD 6TB
 Volumeseriennummer: 84D6-63CE

 Verzeichnis von S:\AAA\samsunghealth

14.12.2024  12:19           915.952 com.samsung.shealth.activity.day_summary.20241214121856.csv
               1 Datei(en),        915.952 Bytes
               0 Verzeichnis(se), 3.274.738.540.544 Bytes frei

S:\AAA\samsunghealth>


If you like, we can talk over Discord....

**Comment by PhilippImhof** [comment]
Thanks for checking that. This is very, very strange. Could you try the following:

```
S:\AAA\samsunghealth> C:/Users/Jens/AppData/Local/Microsoft/WindowsApps/python3.11.exe
>>> import glob
>>> glob.glob("com.samsung.health.floors_climbed.*.csv") 
>>> exit

S:\AAA\samsunghealth> C:
C:\> cd \Users\Jens
C:\Users\Jens> C:/Users/Jens/AppData/Local/Microsoft/WindowsApps/python3.11.exe
>>> import glob
>>> glob.glob("com.samsung.health.floors_climbed.*.csv") 
>>> exit
```

Because, in your first comment, I see you started python in the directory `C:\Users\Jens`, so maybe this is used as the working directory.

**Comment by AstraJens** [comment]
S:\AAA\samsunghealth>C:/Users/Jens/AppData/Local/Microsoft/WindowsApps/python3.11.exe
Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import glob
>>> glob.glob("com.samsung.health.floors_climbed.*.csv")
['com.samsung.health.floors_climbed.20241214121856.csv']
>>> exit
Use exit() or Ctrl-Z plus Return to exit

>>> glob.glob("com.samsung.health.floors_climbed.*.csv")
['com.samsung.health.floors_climbed.20241214121856.csv']
>>>

glob can see the right files....

no, all of the files are in this Directory

S:\AAA\samsunghealth    


this was only the Python Path of the .exe file
C:/Users/Jens/AppData/Local/Microsoft/WindowsApps/python3.11.exe

**Comment by PhilippImhof** [comment]
> no, all of the files are in this Directory
> 
> S:\AAA\samsunghealth

Yes, that's what I got from your listing above.

> this was only the Python Path of the .exe file C:/Users/Jens/AppData/Local/Microsoft/WindowsApps/python3.11.exe

What I am talking about is this:

![Bildschirmfoto 2024-12-14 um 17 16 14](https://github.com/user-attachments/assets/d61cae7d-017c-43c9-93b1-a60f6f391880)

This looks as if you were in C:\Users\Jens when you ran the scripts…

**Comment by AstraJens** [comment]
S:\AAA\samsunghealth>C:/Users/Jens/AppData/Local/Microsoft/WindowsApps/python3.11.exe activity.py
Traceback (most recent call last):
  File "S:\AAA\samsunghealth\activity.py", line 184, in <module>
    data = merge_data(fetch_floor_data(), fetch_calorie_data(), fetch_activity_data())
                                                                ^^^^^^^^^^^^^^^^^^^^^
  File "S:\AAA\samsunghealth\activity.py", line 87, in fetch_activity_data
    int(row["day_time"]) / 1000
    ^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '2023-12-30 00:00:00.000'

S:\AAA\samsunghealth>

###################################################################################

PS S:\aaa\samsunghealth> C:/Users/Jens/AppData/Local/Microsoft/WindowsApps/python3.11.exe activity.py
Traceback (most recent call last):
  File "S:\aaa\samsunghealth\activity.py", line 184, in <module>
    data = merge_data(fetch_floor_data(), fetch_calorie_data(), fetch_activity_data())
                                                                ^^^^^^^^^^^^^^^^^^^^^
  File "S:\aaa\samsunghealth\activity.py", line 87, in fetch_activity_data
    int(row["day_time"]) / 1000
    ^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '2023-12-30 00:00:00.000'
PS S:\aaa\samsunghealth>

**Comment by AstraJens** [comment]
How can i send my files to you?  Discord, Teamspeak? On Discord i make a request if we can speak german ;-)

**Comment by PhilippImhof** [comment]
> S:\AAA\samsunghealth>C:/Users/Jens/AppData/Local/Microsoft/WindowsApps/python3.11.exe activity.py Traceback (most recent call last): File "S:\AAA\samsunghealth\activity.py", line 184, in data = merge_data(fetch_floor_data(), fetch_calorie_data(), fetch_activity_data()) ^^^^^^^^^^^^^^^^^^^^^ File "S:\AAA\samsunghealth\activity.py", line 87, in fetch_activity_data int(row["day_time"]) / 1000 ^^^^^^^^^^^^^^^^^^^^ ValueError: invalid literal for int() with base 10: '2023-12-30 00:00:00.000'

That's the other error. For whatever reason, the timestamp is not stored as a timestamp, but in ISO format.

**Comment by PhilippImhof** [comment]
@AstraJens Just to let you know that I will get back to you as soon as possible to schedule an exchange via Discord – auch auf Deutsch, wenn du möchtest...
